# Funding metadata for LazyPhysicsAndChemistry / LazyLearn

github:
  - lachlanchen

custom:
  - https://chat.lazying.art/donate
  - https://github.com/sponsors/lachlanchen
  - https://paypal.me/RongzhouChen
  - https://lazying.art
